# Generated by Django 2.1.2 on 2018-10-21 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conceptoCrecimientoDemanda',
            fields=[
                ('idccd', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=85)),
                ('crecimientoInicial', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='costosTotalesAnuales',
            fields=[
                ('idcostosTotalesAnuales', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='crecimientoDemanda',
            fields=[
                ('idcrecimientoDemanda', models.IntegerField(primary_key=True, serialize=False)),
                ('crecimiento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('conceptoCrecimientoDemanda_idccd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.conceptoCrecimientoDemanda')),
            ],
        ),
        migrations.CreateModel(
            name='datos_empresa',
            fields=[
                ('id_empresa', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=85)),
                ('dias_produccion', models.IntegerField()),
                ('numero_servicios', models.IntegerField()),
                ('no_socios', models.IntegerField()),
                ('denominacion_social', models.CharField(max_length=105)),
                ('rfc', models.CharField(max_length=13)),
                ('telefono', models.CharField(max_length=12)),
                ('sitio_web', models.CharField(max_length=85)),
                ('email', models.CharField(max_length=85)),
                ('calle_domicilio', models.CharField(max_length=45)),
                ('codigo_postal', models.CharField(max_length=6)),
                ('ciudad_empresa', models.CharField(max_length=90)),
                ('estado_empresa', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='estimacion_crecimiento_anual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_anio', models.IntegerField()),
                ('estimacion', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='estimacion_servicios',
            fields=[
                ('id_suscripcion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('unidad_produccion', models.CharField(max_length=100)),
                ('total_suscripciones', models.IntegerField()),
                ('total_mensual', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='gastos',
            fields=[
                ('idgastos', models.IntegerField(primary_key=True, serialize=False)),
                ('conceptoGastos', models.CharField(max_length=85)),
                ('unidadMedida', models.CharField(max_length=48)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad', models.IntegerField()),
                ('estimacionMensual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimacionAnual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('datos_empresa_id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.datos_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='gastosIndirectos',
            fields=[
                ('idgastosIndirectos', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=100)),
                ('unidadMedida', models.CharField(max_length=100)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad', models.IntegerField()),
                ('estimacionMensual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimacionAnual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('datos_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.datos_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='gastosOperativos',
            fields=[
                ('idgastosOperativos', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=85)),
                ('estimacionMensual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimacionAnual', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='inversiones',
            fields=[
                ('idinversiones', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=85)),
                ('unidad_medida', models.CharField(max_length=85)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal_1', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aportacion_propio', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aportacion_financiacion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal_2', models.DecimalField(decimal_places=2, max_digits=15)),
                ('datos_empresa_id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.datos_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='manoObra',
            fields=[
                ('idManoObra', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=85)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_empleados', models.IntegerField()),
                ('costo_anual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('datos_empresa_id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.datos_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='manoObraComisionesVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=85)),
                ('ventas_mensuales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_empleados', models.IntegerField()),
                ('costo_anual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('datos_empresa_id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.datos_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='manoObraOperativa',
            fields=[
                ('idmanoObraOperativa', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=85)),
                ('unidadMedida', models.CharField(max_length=85)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad', models.IntegerField()),
                ('estimacionMensual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('datos_empresa_id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.datos_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='materiaPrimaInsumos',
            fields=[
                ('idmateriaPrimaInsumos', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=85)),
                ('unidadMedida', models.CharField(max_length=85)),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cantidad', models.IntegerField()),
                ('estimacionMensual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estimacionAnual', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.datos_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='perfil_usuario',
            fields=[
                ('idperfil', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=85)),
                ('apellido_p_usuario', models.CharField(max_length=85)),
                ('apellido_m_usuario', models.CharField(max_length=85)),
                ('rfc_usuario', models.CharField(max_length=12)),
                ('email_usuario', models.CharField(max_length=85)),
                ('telefono_usuario', models.CharField(max_length=85)),
                ('domicilio_usuario', models.CharField(max_length=110)),
                ('colonia_usuario', models.CharField(max_length=85)),
                ('codigo_postal_usuario', models.CharField(max_length=6)),
                ('ciudad_usuario', models.CharField(max_length=90)),
                ('estado_usuario', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='producto_servicio',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('producto_nombre', models.CharField(max_length=65)),
                ('unidad_produccion', models.CharField(max_length=45)),
                ('produccion_mensual', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margen_utilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_publico', models.DecimalField(decimal_places=2, max_digits=5)),
                ('datos_empresa_id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.datos_empresa')),
            ],
        ),
        migrations.CreateModel(
            name='tipoGastoOperativo',
            fields=[
                ('idtipoGasto', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='tiposGastos',
            fields=[
                ('idtipoGastos', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='tiposGastoss',
            fields=[
                ('idtiposGastoss', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='tiposInversiones',
            fields=[
                ('idtipoInversiones', models.IntegerField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=85)),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('idtipoUsuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('no_empresas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('last_access', models.DateField()),
                ('datos_empresas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.tipoUsuario')),
            ],
        ),
        migrations.AddField(
            model_name='perfil_usuario',
            name='usuario_idusuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.Usuario'),
        ),
        migrations.AddField(
            model_name='manoobraoperativa',
            name='servicio_id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.producto_servicio'),
        ),
        migrations.AddField(
            model_name='inversiones',
            name='tiposInversiones_idtipoInversiones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.tiposInversiones'),
        ),
        migrations.AddField(
            model_name='gastosoperativos',
            name='datos_empresa_id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.tipoGastoOperativo'),
        ),
        migrations.AddField(
            model_name='gastosoperativos',
            name='idtipoGasto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.datos_empresa'),
        ),
        migrations.AddField(
            model_name='gastos',
            name='tiposGastos_idtipoGastos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.tiposGastos'),
        ),
        migrations.AddField(
            model_name='estimacion_servicios',
            name='producto_servicio_id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.producto_servicio'),
        ),
        migrations.AddField(
            model_name='estimacion_crecimiento_anual',
            name='producto_servicio_id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.producto_servicio'),
        ),
        migrations.AddField(
            model_name='datos_empresa',
            name='usuario_idusuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.Usuario'),
        ),
        migrations.AddField(
            model_name='crecimientodemanda',
            name='datos_empresa_id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.datos_empresa'),
        ),
        migrations.AddField(
            model_name='costostotalesanuales',
            name='datos_empresa_id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.datos_empresa'),
        ),
        migrations.AddField(
            model_name='costostotalesanuales',
            name='tiposGastoss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud_simulador.tiposGastoss'),
        ),
    ]
